# Generated by Django 2.2.6 on 2019-10-18 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_translations'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producttranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='producttranslation',
            name='master',
        ),
        migrations.DeleteModel(
            name='CategoryTranslation',
        ),
        migrations.DeleteModel(
            name='ProductTranslation',
        ),
    ]
